### PR TITLE
change bundle identifier to distinguish fork from original

### PR DESCRIPTION
**Pull request by core-code**

### CODE REVIEW

**Comment by vectorsigma72** [comment]
Not sure this is a fork. We just move.

**Comment by vectorsigma72** [comment]
> No description provided.

Hi, 
this is not a fork, it is the main repository. We just moved from source forge.

**Comment by core-code** [comment]
if this is the official continuation of the sourceforge project ( https://sourceforge.net/projects/hwsensors3.hwsensors.p/ ) then changing the bundle-id is not necessary. 

however it is not obvious that this is the official continuation at all. can you add a notice on the sourceforge and github site? thanks!

**Comment by vectorsigma72** [comment]
> if this is the official continuation of the sourceforge project ( https://sourceforge.net/projects/hwsensors3.hwsensors.p/ ) then changing the bundle-id is not necessary.
> 
> however it is not obvious that this is the official continuation at all. can you add a notice on the sourceforge and github site? thanks!

I'll tell that to Slice

**Pull request closed without merging**
